### ISSUE TITLE
project status - maintained or abadoned

### ISSUE THREAD

**Issue by ssbarnea** [testing-cabal/testrepository#35]
Based on commit history, open issues and especially already opened PRs, I am inclined to believe that the project is no longer maintained.

If this is true, I would like to be added as maintainer so I can merge few critial fixes (including CI ones) and make a new release.

Is this possible?

**Comment by jelmer** [comment]
I believe the project is maintained, just not very active. That said, more help would be nice. :) Adding @rbtcollins, who is the primary author.

**Comment by ssbarnea** [comment]
I am quite curious to hear back from @rbtcollins as I find the project in a very poor state which would require lots of changes only to bring back the CI to green.

I also found about a fork named **stesrt** at https://github.com/mtreinish/stestr which seems to be very well maintained (with multiple contributors and **working CI**).

Maybe inviting @mtreinish to takeover testr and give it a new life would not sound like a bad idea.

**Comment by rbtcollins** [comment]
The project is team maintained - the testing-cabal org has a number of folk interested in maintaining a few different tools - subunit, testtools, some backports of key libs, testrepository, etc.

The open PRs are all failing CI, and none are blocked on a reviewer that I can see. Similarly for the issues, though the new ones you've opened haven't all been triaged yet.

I'm not paid by my current job to work on this, so it fits in amongst other commitments, but I certainly haven't abandoned it, and as @jelmer says, help is welcomed.

@mtreinish has a different focus - he is solving for Python only - and thats great. I would like to converge eventually, but my recollection of a chat we had in Jan at LCA was that taking over this project as-is wasn't appealing to him - precisely because its aimed at a larger problem.
